version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    command: ['redis-server', '--requirepass', 'redislocal']

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: 'Th3M05tS3cur3P@ssw0rd'
      ACCEPT_EULA: 'Y'
      DB_DATABASE: 'PlantillaAdonisJS'
      DB_USER: 'UserPlantillaAdonisJS'
      DB_PASSWORD: 'Us3rP@ssw0rdAd0n1sJS'
    ports:
      - '1433:1433'
    volumes:
      - ./mssql-init.sh:/usr/config/mssql-init.sh
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & 
        sleep 30 && /usr/config/mssql-init.sh && tail -f /dev/null

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672' # Default RabbitMQ port
      - '15672:15672' # RabbitMQ Management Plugin port
    environment:
      RABBITMQ_DEFAULT_USER: user-rabbitmq
      RABBITMQ_DEFAULT_PASS: password-rabbitmq

volumes:
  mssql-data:
    driver: local
